# Generated by Django 2.1.7 on 2019-03-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='compile_option',
            field=models.CharField(default='', max_length=255),
        ),
    ]
